server:
  port: ${PORT:9092}
spring:
  application:
    name: currency-conversion-service
  datasource:
    url: ${SPRING_DATA_URL:jdbc:mysql://localhost:3306/database?autoReconnect=true&useSSL=false}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME:shefzee}
    password: ${DB_PASSWORD:shef123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
exchange-rate:
  service:
    url: ${EXCHANGE_RATE_URL}/api/exchange-rate